/**
 * Bundled fallback photo index.
 *
 * Used when the dev-server API (/api/photos) is unreachable AND the
 * IndexedDB cache is empty — e.g. a static production build with no
 * middleware. Kept in sync with data/photos.json at build time.
 */
import type { PhotoEntry } from "./photoStore";

const T = "2026-09-29T00:00:00.000Z";

export const FALLBACK_PHOTOS: PhotoEntry[] = [
  { id: "hero-aerial", zone: "hero", src: "/images/villa/hero-aerial.jpg", caption: "The residence, pool and sea horizon.", updatedAt: T },
  { id: "villa-facade", zone: "exterior", src: "/images/villa/villa-facade.jpg", caption: "The residence from the lawn.", updatedAt: T },
  { id: "villa-facade-2", zone: "exterior", src: "/images/villa/villa-facade-2.jpg", caption: "The residence, garden aspect.", updatedAt: T },
  { id: "villa-pool-wide", zone: "exterior", src: "/images/villa/villa-pool-wide.jpg", caption: "Pool terrace and residence.", updatedAt: T },
  { id: "villa-elevated", zone: "exterior", src: "/images/villa/villa-elevated.jpg", caption: "The residence from the garden.", updatedAt: T },
  { id: "grounds-elevated", zone: "exterior", src: "/images/villa/grounds-elevated.jpg", caption: "Grounds, from the upper terrace.", updatedAt: T },
  { id: "grounds-elevated-2", zone: "exterior", src: "/images/villa/grounds-elevated-2.jpg", caption: "Grounds and pool bar.", updatedAt: T },
  { id: "villa-aerial", zone: "exterior", src: "/images/villa/villa-aerial.jpg", caption: "The residence, from above.", updatedAt: T },
  { id: "lawn-pergola", zone: "exterior", src: "/images/villa/lawn-pergola.jpg", caption: "Lawn, pergola and pool.", updatedAt: T },
  { id: "lawn-pool", zone: "exterior", src: "/images/villa/lawn-pool.jpg", caption: "Lawn and pool terrace.", updatedAt: T },
  { id: "pines", zone: "exterior", src: "/images/villa/pines.jpg", caption: "Parasol pine canopy.", updatedAt: T },
  { id: "beach", zone: "exterior", src: "/images/villa/beach.jpg", caption: "Pampelonne, early morning.", updatedAt: T },
  { id: "pool-lawn", zone: "pool", src: "/images/villa/pool-lawn.jpg", caption: "Pool and private lawn.", updatedAt: T },
  { id: "pool-lawn-2", zone: "pool", src: "/images/villa/pool-lawn-2.jpg", caption: "Lawn and pool.", updatedAt: T },
  { id: "pool-terrace", zone: "pool", src: "/images/villa/pool-terrace.jpg", caption: "Pool terrace, sea horizon.", updatedAt: T },
  { id: "pool-terrace-wide", zone: "pool", src: "/images/villa/pool-terrace-wide.jpg", caption: "Pool terrace.", updatedAt: T },
  { id: "pool-panorama", zone: "pool", src: "/images/villa/pool-panorama.jpg", caption: "Pool terrace, sea horizon.", updatedAt: T },
  { id: "pool-bar", zone: "pool", src: "/images/villa/pool-bar.jpg", caption: "Pool bar, sea horizon.", updatedAt: T },
  { id: "pool-bar-2", zone: "pool", src: "/images/villa/pool-bar-2.jpg", caption: "Pool bar.", updatedAt: T },
  { id: "pool-loungers", zone: "pool", src: "/images/villa/pool-loungers.jpg", caption: "Heated pool, pergola lounge.", updatedAt: T },
  { id: "sun-terrace", zone: "pool", src: "/images/villa/sun-terrace.jpg", caption: "Sun terrace.", updatedAt: T },
  { id: "pool-dining-elevated", zone: "pool", src: "/images/villa/pool-dining-elevated.jpg", caption: "Poolside dining terrace.", updatedAt: T },
  { id: "master-bedroom", zone: "level1", src: "/images/villa/master-bedroom.jpg", caption: "Master suite.", updatedAt: T },
  { id: "master-bedroom-2", zone: "level1", src: "/images/villa/master-bedroom-2.jpg", caption: "Master suite, sitting area.", updatedAt: T },
  { id: "upper-terrace", zone: "level1", src: "/images/villa/upper-terrace.jpg", caption: "Upper terrace, sea aspect.", updatedAt: T },
  { id: "salon", zone: "level1", src: "/images/villa/salon.jpg", caption: "Living salon, sea aspect.", updatedAt: T },
  { id: "bath-vanity", zone: "level1", src: "/images/villa/bath-vanity.jpg", caption: "Limestone bathroom, double vanity.", updatedAt: T },
  { id: "bath-tub", zone: "level1", src: "/images/villa/bath-tub.jpg", caption: "Soaking bath.", updatedAt: T },
  { id: "bath-vanity-wide", zone: "level1", src: "/images/villa/bath-vanity-wide.jpg", caption: "Bathroom, vanity run.", updatedAt: T },
  { id: "guest-suite-garden", zone: "ground", src: "/images/villa/guest-suite-garden.jpg", caption: "Guest suite, opening to private lawn.", updatedAt: T },
  { id: "guest-suite-1", zone: "ground", src: "/images/villa/guest-suite-1.jpg", caption: "Guest suite, garden level.", updatedAt: T },
  { id: "guest-suite-2", zone: "ground", src: "/images/villa/guest-suite-2.jpg", caption: "Guest suite.", updatedAt: T },
  { id: "guest-suite-terrace", zone: "ground", src: "/images/villa/guest-suite-terrace.jpg", caption: "Guest suite, terrace aspect.", updatedAt: T },
  { id: "gallery-corridor", zone: "ground", src: "/images/villa/gallery-corridor.jpg", caption: "Gallery corridor.", updatedAt: T },
  { id: "family-wing", zone: "family", src: "/images/villa/family-wing.jpg", caption: "Children's dormitory.", updatedAt: T },
  { id: "summer-bar", zone: "experience", src: "/images/villa/summer-bar.jpg", caption: "Summer bar, garden aspect.", updatedAt: T },
  { id: "outdoor-kitchen", zone: "experience", src: "/images/villa/outdoor-kitchen.jpg", caption: "Travertine outdoor kitchen.", updatedAt: T },
  { id: "pergola-lounge", zone: "experience", src: "/images/villa/pergola-lounge.jpg", caption: "Pergola lounge.", updatedAt: T },
  { id: "pergola-lounge-2", zone: "experience", src: "/images/villa/pergola-lounge-2.jpg", caption: "Pergola lounge, pool edge.", updatedAt: T },
  { id: "pergola-pool-side", zone: "experience", src: "/images/villa/pergola-pool-side.jpg", caption: "Pergola lounge.", updatedAt: T },
  { id: "pergola-wide", zone: "experience", src: "/images/villa/pergola-wide.jpg", caption: "Pergola lounge, poolside.", updatedAt: T },
  { id: "pergola-detail", zone: "experience", src: "/images/villa/pergola-detail.jpg", caption: "Timber pergola.", updatedAt: T },
  { id: "pergola-lounge-interior", zone: "experience", src: "/images/villa/pergola-lounge-interior.jpg", caption: "Pergola lounge.", updatedAt: T },
  { id: "pergola-lounge-interior-2", zone: "experience", src: "/images/villa/pergola-lounge-interior-2.jpg", caption: "Pergola lounge.", updatedAt: T },
  { id: "dining-terrace", zone: "experience", src: "/images/villa/dining-terrace.jpg", caption: "Alfresco dining terrace.", updatedAt: T },
  { id: "dining-terrace-2", zone: "experience", src: "/images/villa/dining-terrace-2.jpg", caption: "Dining terrace from the lawn.", updatedAt: T },
  { id: "be-salon-sea", zone: "level1", src: "/images/villa/be-salon-sea.jpg", caption: "Salon, opening to the sea.", updatedAt: T },
  { id: "be-suite-sea", zone: "level1", src: "/images/villa/be-suite-sea.jpg", caption: "Guest suite, sea aspect.", updatedAt: T },
  { id: "be-pergola-dining", zone: "experience", src: "/images/villa/be-pergola-dining.jpg", caption: "Dining beneath the pergola.", updatedAt: T },
  { id: "be-gallery-hall", zone: "ground", src: "/images/villa/be-gallery-hall.jpg", caption: "Gallery hall.", updatedAt: T },
  { id: "be-dining-room", zone: "level1", src: "/images/villa/be-dining-room.jpg", caption: "Dining room.", updatedAt: T },
  { id: "be-kitchen", zone: "level1", src: "/images/villa/be-kitchen.jpg", caption: "Kitchen.", updatedAt: T },
  { id: "be-suite-twin", zone: "ground", src: "/images/villa/be-suite-twin.jpg", caption: "Guest suite, twin aspect.", updatedAt: T },
  { id: "st-facade-glass", zone: "exterior", src: "/images/villa/st-facade-glass.jpg", caption: "The residence, south elevation.", updatedAt: T },
  { id: "st-salon-piano", zone: "level1", src: "/images/villa/st-salon-piano.jpg", caption: "Salon, piano corner.", updatedAt: T },
  { id: "be-suite-corridor", zone: "ground", src: "/images/villa/be-suite-corridor.jpg", caption: "Suite corridor.", updatedAt: T },
  { id: "st-pool-lawn-sea", zone: "pool", src: "/images/villa/st-pool-lawn-sea.jpg", caption: "Pool lawn, sea horizon.", updatedAt: T },
  { id: "be-bath-limestone", zone: "level1", src: "/images/villa/be-bath-limestone.jpg", caption: "Limestone bathroom.", updatedAt: T },
  { id: "st-pool-deck", zone: "pool", src: "/images/villa/st-pool-deck.jpg", caption: "Pool deck.", updatedAt: T },
  { id: "be-aerial-pool", zone: "exterior", src: "/images/villa/be-aerial-pool.jpg", caption: "Pool and grounds, from above.", updatedAt: T },
  { id: "st-sitting-art", zone: "level1", src: "/images/villa/st-sitting-art.jpg", caption: "Sitting room.", updatedAt: T },
  { id: "be-suite-twin-2", zone: "ground", src: "/images/villa/be-suite-twin-2.jpg", caption: "Guest suite.", updatedAt: T },
  { id: "be-suite-panorama", zone: "level1", src: "/images/villa/be-suite-panorama.jpg", caption: "Suite, panoramic aspect.", updatedAt: T },
  { id: "be-suite-garden-doors", zone: "ground", src: "/images/villa/be-suite-garden-doors.jpg", caption: "Suite, opening to the garden.", updatedAt: T },
  { id: "st-dining-set", zone: "experience", src: "/images/villa/st-dining-set.jpg", caption: "Alfresco dining, set for twelve.", updatedAt: T },
  { id: "st-pergola-flowers", zone: "experience", src: "/images/villa/st-pergola-flowers.jpg", caption: "Pergola dining.", updatedAt: T },
  { id: "be-facade-lawn", zone: "exterior", src: "/images/villa/be-facade-lawn.jpg", caption: "The residence from the lawn.", updatedAt: T },
  { id: "be-terrace-sea", zone: "level1", src: "/images/villa/be-terrace-sea.jpg", caption: "Upper terrace, sea aspect.", updatedAt: T },
  { id: "st-bedroom-31", zone: "ground", src: "/images/villa/st-bedroom-31.jpg", caption: "Guest suite.", updatedAt: T },
  { id: "st-bedroom-32", zone: "ground", src: "/images/villa/st-bedroom-32.jpg", caption: "Suite with sitting area.", updatedAt: T },
  { id: "st-bedroom-35", zone: "ground", src: "/images/villa/st-bedroom-35.jpg", caption: "Guest suite.", updatedAt: T },
  { id: "st-bedroom-36", zone: "ground", src: "/images/villa/st-bedroom-36.jpg", caption: "Guest suite.", updatedAt: T },
  { id: "st-bedroom-38", zone: "ground", src: "/images/villa/st-bedroom-38.jpg", caption: "Guest suite.", updatedAt: T },
  { id: "st-suite-art", zone: "level1", src: "/images/villa/st-suite-art.jpg", caption: "Guest suite.", updatedAt: T },
  { id: "st-bath-sea", zone: "level1", src: "/images/villa/st-bath-sea.jpg", caption: "Bathroom, sea aspect.", updatedAt: T },
  { id: "st-kitchen", zone: "level1", src: "/images/villa/st-kitchen.jpg", caption: "Kitchen.", updatedAt: T },
  { id: "st-gym", zone: "wellness", src: "/images/villa/st-gym.jpg", caption: "Gym.", updatedAt: T },
  { id: "st-bbq", zone: "experience", src: "/images/villa/st-bbq.jpg", caption: "Outdoor kitchen.", updatedAt: T },
  { id: "st-terrace-bougainvillea", zone: "exterior", src: "/images/villa/st-terrace-bougainvillea.jpg", caption: "Terrace.", updatedAt: T },
  { id: "st-garden-sea", zone: "exterior", src: "/images/villa/st-garden-sea.jpg", caption: "Gardens, sea horizon.", updatedAt: T },
  { id: "st-massage", zone: "wellness", src: "/images/villa/st-massage.jpg", caption: "Massage room.", updatedAt: T },
  { id: "st-hammam", zone: "wellness", src: "/images/villa/st-hammam.jpg", caption: "Hammam.", updatedAt: T },
];
